package www.hales.iscool;


import static com.codename1.ui.CN.*;

import com.codename1.social.FacebookConnect;
import com.codename1.social.GoogleConnect;
import com.codename1.social.Login;
import com.codename1.ui.*;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;

import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class chat {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form stooopid = new Form("HAI",new BorderLayout());
        stooopid.add(LogInForm());
        stooopid.show();
    }

    public Form LogInForm() {
        Form loginForm = new Form();

        // the blue theme styles the title area normally this is good but in this case we don't want the blue bar at the top
        loginForm.getTitleArea().setUIID("Container");
        loginForm.setLayout(new BorderLayout());
        loginForm.setUIID("MainForm");
        Container cnt = new Container(new BoxLayout(BoxLayout.Y_AXIS));
        cnt.setUIID("Padding");

        Button loginWithGoogle = new Button("Sign in with Google");
        loginWithGoogle.addActionListener((e) -> Log.p("Clicked"));


        loginWithGoogle.setUIID("LoginButtonGoogle");
        Button loginWithFacebook = new Button("Sign in with Facebook");
        loginWithFacebook.addActionListener((e) -> Log.p("Clicked"));

        loginWithFacebook.setUIID("LoginButtonFacebook");
        Style iconFontStyle = UIManager.getInstance().getComponentStyle("IconFont");
        loginWithFacebook.setIcon(FontImage.create(" \ue96c ", iconFontStyle));
        loginWithGoogle.setIcon(FontImage.create(" \ue976 ", iconFontStyle));
        cnt.addComponent(loginWithGoogle);
        cnt.addComponent(loginWithFacebook);
        loginWithGoogle.addActionListener((e) -> {
            doLogin(GoogleConnect.getInstance());
        });
        loginWithFacebook.addActionListener((e) -> {
            doLogin(FacebookConnect.getInstance());
        });
        loginForm.addComponent(BorderLayout.SOUTH, cnt);
        return(loginForm);
    }

    void doLogin(Login lg) {
        // TODO...
    }


    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
